services:
  # 1. THE DATABASE
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # 2. THE BACKEND (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/backend/static
    expose:
      - "8000"
    environment:
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  # 3. THE FRONTEND + NGINX
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/backend/static
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: