sonar.projectKey=bcsanup-github_project-devops
sonar.organization=bcsanup-github
sonar.projectName=My Fullstack App
sonar.host.url=https://sonarcloud.io

# We removed 'sonar.modules' to stop the "double indexing" error
sonar.sources=.

# This tells the scanner to skip folders that don't contain your actual code
sonar.exclusions=**/node_modules/**, **/venv/**, **/.git/**, **/migrations/**, **/tests/**