sonar.projectKey=bcsanup-github_project-devops

sonar.projectName=My Fullstack App
sonar.organization=bcsanup-github
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.modules=backend,frontend
sonar.exclusions=**/node_modules/**, **/venv/**, **/.git/**