upstream api {
    server backend:8000;
}

server {
    listen 80;

    # Frontend - Serve React Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Backend - Proxy API requests to Django
    location /api/ {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Backend - Django Admin
    location /admin/ {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Django Static Files (Phase 2)
    location /static/backend/ {
        alias /app/backend/static/;
    }
}